name: Build and Push SCXA SolrCloud Image

on:
  push:
    paths:
      - "scxa-solrcloud/Dockerfile"

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-20.04
    env:
      IMAGE_NAME: scxa-solrcloud

    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2

    - name: Read upstream tag without version
      id: gettag
      run: echo "::set-output name=tag::$(head -n 1 scxa-solrcloud/Dockerfile | awk -F':' '{print $2}' | awk -F'-' 'BEGIN { OFS="-" } {$NF=""; print $0}')"

    - name: Build image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: latest ${{ steps.gettag.outputs.tag }}
        dockerfiles: |
          ./scxa-solrcloud/Dockerfile

    - name: Push to Quay
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/ebigxa
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}

    - name: Use the image
      run: echo "New image has been pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
